### ISSUE TITLE
KafkaTopic entity is not being created

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kafka#142]
As per this [definition](https://github.com/newrelic/entity-definitions/blob/main/definitions/infra-kafkatopic/definition.yml) and this [inventory rule](https://source.datanerd.us/meatballs/backend/blob/b4c5ef4ce5339ad9eba51cd1ce685fe0f2d13b40/shared/inventory/metadata.go#L282), a KafkaTopic entity should be being generated. However, this is not happening apparently because the KafkaTopic reported entity does not have a `topic.name` attribute, that the inventory rule is trying to fetch.

We should verify whether this is correct and if so, start adding `topic.name` to the KafkaTopic inventory.

**Comment by paologallinaharbur** [comment]
Adding the inventory is quite trivial and can be done as follow:
```go
diff --git a/src/topic/topic_collection.go b/src/topic/topic_collection.go
index 07d9280..160867c 100644
--- a/src/topic/topic_collection.go
+++ b/src/topic/topic_collection.go
@@ -268,5 +268,9 @@ func populateTopicInventory(t *Topic) []error {
                }
        }
 
+       if err := t.Entity.SetInventoryItem("topic.name", "value", t.Name); err != nil {
+               errors = append(errors, err)
+       }
+
        return errors
 }
diff --git a/src/topic/topic_collection_test.go b/src/topic/topic_collection_test.go
index 966ef9d..0f71658 100644
--- a/src/topic/topic_collection_test.go
+++ b/src/topic/topic_collection_test.go
@@ -137,6 +137,9 @@ func TestPopulateTopicInventory(t *testing.T) {
                "topic.flush.messages": {
                        "value": "12345",
                },
+               "topic.name": {
+                       "value": "test",
+               },
        }
 
        errors := populateTopicInventory(myTopic)

```

The Entity type also exists in the backend:
<img width="703" alt="Screenshot 2022-10-20 at 11 35 26" src="https://user-images.githubusercontent.com/43335750/196912990-64d811f0-2e83-4684-ab06-3f6533437925.png">


However, it was an entity that has been never created since there is no dashboard, summary, or golden metrics related -> https://github.com/newrelic/entity-definitions/tree/main/definitions/infra-kafkatopic
 
Therefore it would not make much sense to add it now. Moreover, I do not like that much to carry on supporting the inventory workaround

**Comment by paologallinaharbur** [comment]
No dashboard is present in the legacy repository 
 - https://source.datanerd.us/Pegasus/infra-summary/tree/master/nerdlets/generic-overview/templates

Nor can be found in the legacy of the legacy
 - https://source.datanerd.us/beyond/overview-templates-generator/tree/96410a104ddc0bf38c72f16ea7e4c2eb14cac67c/entities/overview/on-host
